import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("the static UI does not require inline styles under the self-only CSP", async () => {
  const [html, script, styles] = await Promise.all([
    readFile(new URL("../public/index.html", import.meta.url), "utf8"),
    readFile(new URL("../public/app.js", import.meta.url), "utf8"),
    readFile(new URL("../public/styles.css", import.meta.url), "utf8"),
  ]);
  assert.doesNotMatch(html, /\sstyle\s*=/iu);
  assert.doesNotMatch(html, /<style\b/iu);
  assert.doesNotMatch(script, /\sstyle\s*=/iu);
  assert.doesNotMatch(script, /\.style(?:\.|\[)/u);
  assert.doesNotMatch(script, /\.style\s*=/u);
  assert.doesNotMatch(script, /setAttribute\(\s*["']style["']/u);
  assert.doesNotMatch(script, /\.cssText\b|\.setProperty\(|\.insertRule\(/u);
  assert.match(script, /<progress\b/u);
  assert.match(script, /task\.model/u);
  assert.match(script, /task\.effort/u);
  assert.match(script, /task\.costEstimate/u);
  assert.match(script, /summary\.totalCostEstimate/u);
  assert.match(script, /agent\.ownCostEstimate/u);
  assert.match(script, /agent\.subtreeCostEstimate/u);
  assert.match(script, /session\.projectPath/u);
  assert.match(script, /data-session-view/u);
  assert.match(script, /selectedDay:\s*null/u);
  assert.match(script, /data-session-day=/u);
  assert.match(script, /button\.dataset\.sessionDay === state\.selectedDay/u);
  assert.match(script, /\?day=\$\{encodeURIComponent\(day\)\}/u);
  assert.match(script, /preferredTimelineDay\(state\.selectedId\)/u);
  assert.match(script, /nextView === "time" \? preferredTimelineDay\(state\.selectedId\) : null/u);
  assert.match(script, /snapshot\.scope\?\.type === "day"/u);
  assert.match(script, /refreshTimelineNavigation\(selectionVersion\)/u);
  assert.match(script, /renderSessionsByTime/u);
  assert.match(script, /formatTimelineUsageCost\(month\.usage, month\.costEstimate\)/u);
  assert.match(script, /formatTimelineUsageCost\(day\.usage, day\.costEstimate\)/u);
  assert.match(script, /formatTokens\(session\.usage\?\.totalTokens\)/u);
  assert.match(script, /formatTimelineSessionCost\(session\.costEstimate\?\.amountUsd\)/u);
  assert.match(html, /订阅标准价等值/u);
  assert.match(script, /订阅标准价等值/u);
  assert.match(script, /featureCoverage/u);
  assert.match(script, /verified usage unit/u);
  assert.doesNotMatch(script, /标准 API 短上下文|API 等值/u);
  assert.doesNotMatch(script, /summary\.status === "partial" \? "≥"/u);
  assert.match(script, /minimumFractionDigits:\s*2,[\s\S]*?maximumFractionDigits:\s*2/iu);
  assert.match(script, /document\.startViewTransition/u);
  assert.match(script, /prefers-reduced-motion: reduce/u);
  assert.match(script, /formatMonthLabel/u);
  assert.match(script, /formatDayLabel/u);
  assert.match(script, /timeline\.months/u);
  assert.match(script, /replace\(\/\^\\\\\\\\\\\?\\\\\/u, ""\)/u);
  assert.match(script, /const sessionUsage = snapshot\.summary\.totalUsage/u);
  assert.match(script, /formatCacheHitRate\(sessionUsage\)/u);
  assert.match(script, /formatCacheHitRate\(agent\.ownUsage\)/u);
  assert.match(script, /formatCacheHitRate\(task\.deltaUsage\)/u);
  assert.doesNotMatch(script, /data-preview-thread|<th>指令<\/th>/u);
  assert.match(script, /cached \/ input/u);
  assert.match(html, /id="session-cost"/u);
  assert.match(html, />Total token<\/span>/u);
  assert.match(html, /根智能体与全部后代 · 实时汇总/u);
  assert.match(script, /elements\["hero-total"\]\.textContent = formatTokens\(snapshot\.summary\.totalUsage\?\.totalTokens\)/u);
  assert.match(html, /id="input-total"/u);
  assert.match(html, /id="output-total"/u);
  assert.match(html, /id="cache-hit-rate"/u);
  assert.match(html, /id="quota-refresh"/u);
  assert.match(html, /data-lucide="refresh-cw"/u);
  assert.match(html, /src="\/vendor\/lucide\.min\.js"/u);
  assert.doesNotMatch(html, /<button[^>]+id="quota-refresh"[^>]*>[\s\S]*?<path\b/iu);
  assert.match(script, /window\.lucide\?\.createIcons/u);
  assert.match(script, /\/api\/quota\?refresh=1/u);
  assert.match(script, /quotaRefreshing/u);
  assert.match(styles, /\.quota-refresh\.refreshing svg/u);
  assert.match(html, /content="light"/u);
  assert.match(html, /<img class="brand-mark" src="\/assets\/mizuki\.png" alt="" aria-hidden="true">/u);
  assert.doesNotMatch(html, /class="brand-mark"[^>]*><span/u);
  assert.match(html, /id="session-project"/u);
  assert.match(html, /data-session-view="project"/u);
  assert.match(html, /data-session-view="time"/u);
  assert.match(script, /branch\.className = `agent-branch depth-\$\{Math\.min\(depth, 6\)\}`/u);
  assert.match(script, /childContainer\.className = "agent-children"/u);
  assert.match(script, /role-badge/u);
  assert.match(script, /<colgroup>/u);
  assert.match(script, /aria-label="\$\{dayScope \? "当日任务活动" : "任务记录"\}；任务与状态列固定/u);
  assert.match(script, /task\.firstRequestAt/u);
  assert.match(script, /task\.lastRequestAt/u);
  assert.match(script, /task\.requestCount/u);
  assert.match(script, /<th>推理强度<\/th>/u);
  assert.match(script, /renderRequestRow\(request, task\?\.effort\)/u);
  assert.doesNotMatch(script, /<th>Coverage<\/th>/u);
  assert.match(script, />服务层级<\/th>/u);
  assert.match(script, /class="request-model"/u);
  assert.match(script, /serviceTierLabel\(request\.serviceTier, request\.costEstimate\)/u);
  assert.match(script, /const TASK_PAGE_SIZE = 10/u);
  assert.match(script, /const REQUEST_PAGE_SIZE = 10/u);
  assert.match(script, /class="request-count-pill"/u);
  assert.match(script, /class="task-pagination pagination-bar"/u);
  assert.match(script, /class="request-pagination pagination-bar"/u);
  assert.match(script, /data-request-collapse/u);
  assert.match(script, /data-request-page-jump/u);
  assert.match(script, /data-task-page-jump/u);
  assert.match(script, /limit: String\(REQUEST_PAGE_SIZE\), page: String\(requestedPage\)/u);
  assert.match(script, /return "standard"/u);
  assert.match(script, /`fast · \$\{formatMultiplier\(multiplier\)\} 倍率`/u);
  assert.match(script, /return normalized === "fast" \? "fast" : "standard"/u);
  assert.doesNotMatch(script, /normalized === "fast" \|\| normalized === "priority"/u);
  assert.match(script, /const value = estimate\?\.amountUsd/u);
  assert.doesNotMatch(script, /estimate\?\.status === "estimated" \? estimate\.amountUsd : null/u);
  assert.match(script, /function requestCostEstimateTitle\(/u);
  assert.match(script, /data-task-toggle/u);
  assert.match(script, /requestDetails:\s*new Map\(\)/u);
  assert.match(script, /\/tasks\/\$\{encodeURIComponent\(threadId\)\}\/\$\{encodeURIComponent\(turnId\)\}\/requests/u);
  assert.match(script, /refreshStaleOpenRequestDetails/u);
  assert.match(script, /projectionGeneration/u);
  assert.match(script, /<caption class="\$\{dayScope \? "visually-hidden" : ""\}">\$\{dayScope \? "当日任务活动" : "任务记录"\}<\/caption>/u);
  assert.match(styles, /\.task-table caption\.visually-hidden\s*\{[^}]*position:\s*absolute;[^}]*clip-path:\s*inset\(50%\)/isu);
  assert.doesNotMatch(script, /<th>推理<\/th>|col-reasoning/u);
  assert.match(script, /class="task-name-head"/u);
  assert.match(script, /class="task-status-head"/u);
  assert.match(script, /class="task-status-cell"/u);
  assert.match(styles, /--parchment:\s*#f4f1ea/iu);
  assert.match(styles, /--text-identifier:\s*10px/iu);
  assert.match(styles, /--text-utility:\s*11px/iu);
  assert.match(styles, /--text-label:\s*12px/iu);
  assert.match(styles, /--text-body:\s*14px/iu);
  assert.match(styles, /--text-data:\s*12px/iu);
  assert.match(styles, /--text-entity:\s*20px/iu);
  assert.doesNotMatch(styles, /font-size:\s*(?:8|9)px\b/iu);
  assert.match(styles, /\.eyebrow\s*\{[^}]*font-family:\s*var\(--body\)/isu);
  assert.match(styles, /\.role-badge\s*\{[^}]*font-family:\s*var\(--body\)/isu);
  assert.match(styles, /\.task-table th\s*\{[^}]*font-family:\s*var\(--body\)/isu);
  assert.match(styles, /\.task-table th\s*\{[^}]*text-align:\s*center/isu);
  assert.match(styles, /\.task-table td\s*\{[^}]*font-family:\s*var\(--mono\)/isu);
  assert.match(styles, /\.task-table td\s*\{[^}]*text-align:\s*center/isu);
  assert.match(styles, /\.activity-group \.metric-card\s*\{[^}]*align-items:\s*center;[^}]*justify-content:\s*center;[^}]*text-align:\s*center/isu);
  assert.match(styles, /\.task-table\s*\{[^}]*min-width:\s*1420px/isu);
  assert.match(styles, /\.task-table\.day-scope\s*\{[^}]*min-width:\s*1447px/isu);
  assert.match(styles, /\.model-cell code,\s*\.request-model\s*\{[^}]*var\(--blue\)[^}]*var\(--blue-soft\)/isu);
  assert.match(styles, /\.request-cost\.partial\s*\{[^}]*var\(--gold\)/isu);
  assert.match(styles, /\.agent-stat span,\s*\.agent-stat strong\s*\{[^}]*text-align:\s*center/isu);
  assert.match(styles, /\.session-identity\s*\{[^}]*min-width:\s*0/isu);
  assert.match(styles, /\.session-identity h2\s*\{[^}]*overflow:\s*hidden;[^}]*text-overflow:\s*ellipsis;[^}]*white-space:\s*nowrap/isu);
  assert.doesNotMatch(styles, /\.session-identity h2\s*\{[^}]*text-wrap:\s*balance/isu);
  assert.match(styles, /\.session-item strong\s*\{[^}]*overflow:\s*hidden;[^}]*text-overflow:\s*ellipsis;[^}]*white-space:\s*nowrap/isu);
  assert.doesNotMatch(styles, /\.session-item strong\s*\{[^}]*-webkit-line-clamp/isu);
  assert.match(styles, /\.time-session-project\s*\{[^}]*overflow:\s*hidden;[^}]*text-overflow:\s*ellipsis;[^}]*white-space:\s*nowrap/isu);
  assert.match(styles, /\.time-session-cost\s*\{[^}]*flex:\s*0 0 auto;[^}]*white-space:\s*nowrap/isu);
  assert.match(styles, /\.role-reviewer/u);
  assert.match(styles, /\.role-test-worker/u);
  assert.match(styles, /--lineage-rail-offset:\s*18px/iu);
  assert.match(styles, /--lineage-elbow-width:\s*14px/iu);
  assert.match(styles, /\.agent-children\s*\{[^}]*margin-left:\s*var\(--lineage-rail-offset\)[^}]*padding-left:\s*var\(--lineage-elbow-width\)/isu);
  assert.match(styles, /@media\s*\(max-width:\s*720px\)[\s\S]*?\.agent-tree\s*\{[^}]*--lineage-rail-offset:\s*10px;[^}]*--lineage-elbow-width:\s*8px/iu);
  assert.match(styles, /\.task-table \.task-name-head,\s*\.task-table \.task-name-cell\s*\{[^}]*position:\s*sticky;[^}]*left:\s*0/isu);
  assert.match(styles, /\.task-table \.task-status-head,\s*\.task-table \.task-status-cell\s*\{[^}]*position:\s*sticky;[^}]*left:\s*160px/isu);
  assert.match(styles, /--scroll-thumb:\s*#cbbdaf/iu);
  assert.match(styles, /--scroll-thumb-hover:\s*#baa99b/iu);
  assert.match(styles, /--scroll-thumb-active:\s*#aa9788/iu);
  assert.match(styles, /\*::?-webkit-scrollbar\s*\{[^}]*width:\s*8px;[^}]*height:\s*8px/isu);
  assert.match(styles, /\*::?-webkit-scrollbar-thumb:hover\s*\{[^}]*var\(--scroll-thumb-hover\)/isu);
  assert.match(styles, /\*::?-webkit-scrollbar-thumb:active\s*\{[^}]*var\(--scroll-thumb-active\)/isu);
  assert.match(styles, /\*::?-webkit-scrollbar-button\s*\{[^}]*display:\s*none;[^}]*width:\s*0;[^}]*height:\s*0/isu);
  assert.match(styles, /\.task-table-wrap:focus-visible/iu);
  assert.match(styles, /\.task-table-wrap\s*\{[^}]*container-type:\s*inline-size/isu);
  assert.match(styles, /\.task-table caption\s*\{[^}]*position:\s*sticky;[^}]*left:\s*0;[^}]*100cqw/isu);
  assert.match(styles, /\.task-request-details\s*\{[^}]*background:/isu);
  assert.match(styles, /\.request-audit-shell\s*\{[^}]*width:\s*100%;[^}]*max-width:\s*100%/isu);
  assert.match(styles, /\.request-audit-scroll\s*\{[^}]*overflow-x:\s*auto/isu);
  assert.match(styles, /\.task-request-panel\s*\{[^}]*grid-template-rows:\s*0fr;[^}]*transition:/isu);
  assert.match(styles, /\.task-request-row\[data-open="true"\] \.task-request-panel\s*\{[^}]*grid-template-rows:\s*1fr/isu);
  assert.match(styles, /\.request-grip-lines\s*\{[^}]*box-shadow:\s*0 -4px 0 currentColor, 0 4px 0 currentColor/isu);
  assert.match(styles, /\.task-request-toggle \.request-count-pill\s*\{[^}]*border-radius:\s*999px/isu);
  assert.match(styles, /\.pagination-bar\s*\{/u);
  assert.match(styles, /font-variant-numeric:\s*tabular-nums/iu);
  assert.match(styles, /prefers-reduced-motion/u);
  assert.match(styles, /::details-content/u);
  assert.match(styles, /view-transition-name:\s*workspace-content/u);
  assert.match(styles, /::view-transition-new\(workspace-content\)/u);
});

test("live updates preserve keyed interaction containers instead of rebuilding them", async () => {
  const script = await readFile(new URL("../public/app.js", import.meta.url), "utf8");
  const renderDashboard = extractFunction(script, "renderDashboard", "renderQuota");
  const updateAgentBranch = extractFunction(script, "updateAgentBranch", "agentNodeClass");
  const patchAgentTasks = extractFunction(script, "patchAgentTasks", "patchTaskRows");

  assert.match(script, /function patchAgentBranches\(/u);
  assert.match(script, /branch\.dataset\.agentId = agent\.threadId/u);
  assert.match(script, /summary\.dataset\.agentAnchorId = agent\.threadId/u);
  assert.match(script, /row\.dataset\.taskId = task\.turnId/u);
  assert.match(script, /function captureVisualAnchor\(/u);
  assert.match(script, /function restoreVisualAnchor\(/u);
  assert.match(script, /window\.scrollBy\(0, delta\)/u);
  assert.match(script, /function patchSessionNavigation\(/u);
  assert.match(script, /function syncSessionSelection\(/u);
  assert.match(script, /data-session-group-key/u);
  assert.match(script, /data-time-month/u);
  assert.match(script, /data-time-day/u);
  assert.match(script, /const interaction = captureSessionListInteraction\(\)/u);
  assert.match(script, /restoreSessionListInteraction\(interaction\)/u);
  assert.match(script, /selectionVersion !== state\.selectionVersion/u);
  assert.match(script, /day !== state\.selectedDay/u);

  assert.doesNotMatch(script, /elements\["agent-tree"\]\.innerHTML\s*=\s*renderBranch/u);
  assert.doesNotMatch(renderDashboard, /renderSessions\(/u);
  assert.match(renderDashboard, /patchSessionNavigation\(previousSession, nextSession\)/u);
  assert.doesNotMatch(updateAgentBranch, /\.open\s*=|setAttribute\([^\n]*["']open["']/u);
  assert.match(patchAgentTasks, /if \(!tableWrap\)/u);
  assert.doesNotMatch(patchAgentTasks, /tableWrap\.innerHTML\s*=/u);
});

function extractFunction(source, name, nextName) {
  const match = source.match(new RegExp(`function ${name}\\([^)]*\\) \\{([\\s\\S]*?)\\n\\}\\n\\nfunction ${nextName}\\(`, "u"));
  assert.ok(match, `expected to find ${name} before ${nextName}`);
  return match[1];
}
